---
title: Tshidiso Mofokeng
---

<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-FEVK27LWND"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-FEVK27LWND');
</script>

# About me

Tshidiso is an aspiring economist who currently holds a undergraduate degree at the University of Pretoria in BCom Econometrics. He has also recently completed a 10 week exchange student program at Fordham University in Emerging Markets and Country Risk Analysis within the field of International Political Economy & Development in New York. 

Tshidiso is a South African aspiring economist whose areas of research are economic policy from a monetary and fiscal perspective as well as macroeconomic modelling. He recently completed his honours research thesis which assessed what the drivers of access to credit in South Africa are at an individual level. 